# Generated by Django 3.2.8 on 2021-10-06 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SideBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('display_type', models.PositiveIntegerField(choices=[(1, 'Html'), (2, 'Latest Songs'), (3, 'Hottest Songs')], default=1, verbose_name='Display type')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Normal'), (0, 'Hide')], default=1, verbose_name='Status')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'Sidebar',
                'verbose_name_plural': 'Sidebar',
            },
        ),
    ]
