# Generated by Django 3.2.5 on 2021-07-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='display_type',
            field=models.PositiveIntegerField(choices=[(1, 'Html'), (2, 'Latest Songs'), (3, 'Hottest Songs')], default=1, verbose_name='Display type'),
        ),
    ]
