# Generated by Django 2.1.7 on 2022-02-07 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Normal'), (0, 'Delete')], default=1, verbose_name='Status')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artist',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Normal'), (0, 'Delete')], default=1, verbose_name='Status')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SongPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Normal'), (0, 'Delete')], default=1, verbose_name='Status')),
                ('audio', models.FileField(blank=True, null=True, upload_to='', verbose_name='Song')),
                ('picture', models.ImageField(upload_to='', verbose_name='Album Photo')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('pv', models.PositiveIntegerField(default=1)),
                ('uv', models.PositiveIntegerField(default=1)),
                ('artist', models.ManyToManyField(to='PopMusic.Artist', verbose_name='Artist')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PopMusic.Category', verbose_name='Category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'Song Posts',
                'verbose_name_plural': 'Song Posts',
                'ordering': ['-id'],
            },
        ),
    ]
